server:
  port: ${PORT:0}
spring:
  application:
    name: ms-cart-2024
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://db-sqlserver-cart:1433;databaseName=db_cart
#    url: jdbc:sqlserver://localhost:1433;databaseName=db_cart
    username: sa
    password: '1a.2b.3c.'
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:ms-cart-2024
#    username: sa
#    password: ''
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
    show-sql: true
  sql:
    init:
      mode: always
      platform: sql
  config:
    import:
    - configserver:http://ms-config-server:8888
#    - configserver:http://localhost:8888
  profiles:
    active:
      - dev
  boot:
    admin:
      client:
        enabled: true
        url: http://ms-sba-server:8086
#        url: http://localhost:8086
        username: admin
        password: admin
  zipkin:
    enabled: true
    base-url: http://ms-zipkin-server:9411
#    base-url: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://ms-discovery-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 3s
    instances:
      product:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 5s
    instances:
      product:
        base-config: defecto