server:
  port: 8002
spring:
  application:
    name: ms-cart-2024
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ms-cart-2024
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    #    defer-datasource-initialization: true
    #    hibernate:
    #      ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': true
        '[use_sql_comments]': false
        '[format_sql]': false
    show-sql: true
  config:
    import:
      - configserver:http://localhost:8888
      #- configserver:http://ms-config-server:8888
  profiles:
    active:
      - dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://ms-discovery-server:8761/eureka